package algorithmicTextbookTrack;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class BA9F {
	public static void main(String args[])
	   {
	      String sub;
	      String string  = "ATCAAGCCAGATAAGAGGTTGATTAATATACCCATAAAAGCTACGGATCATTAACGAGGATTCTGGACTCGTACAACTAGCTGCGAGCTAACACGAAGAAGGCTAAGTTCAGCACTCAATTTGCCTTGCTAAGTTTGTGTCTCGCAGTACACGTCACGATGTTGATTTTTCGTACGCCGTAGAGTAGTCGGACTACTCACCGCGCCAGGAAAAACGCGAGGCACGGGACTGACCCACTTACCCGCGAAGGTTTACACGAACGAACAGTGTTATCCCTGTTACAAACAAAGCATCACGCAGGCAGTACCGCTAGGCGATCCATTCATTTAAGGGCCGGCCTGTTACCCGTACTCCCCCTAAGGAAGAATGGGATCAAGCGACAATAAGCTAAATAGTTAATGACTTGGTTCTGCAATGGCAGATAGGCTTTGGAAACGACTCGAATGGGACAAGGGTGTGACGGGAGGATTTGCATCCGCGCGAACGACTCTTGGAATTGGGGTCGATATTGATCGTTTAGCCCATAATCGCGCATTGCCGCTCGATTCCAGAACTGTTAGCCCAGCGAGAACAACTCGTAAACAGCCAAAAACGGTGTCCGGTCAGTGCAGTCGAGACCCTAAACGGATTTTCGCAACCGACATAAGCTTTTTAGAGGG";
	      String string2 = "TTTAAGGGTTTAGTGGCCTGCCATATTCCTGGATACAGGGTGTTGCGTAGCACGATAGACTATAAGACGCATCTATGCTTATAATCCGACGGCTTTCAGTCGGAATGCACAGCTTCAAATAGCGCTAAGGTGAAATGCAATATCCGTTCGCGCTCTAGGTTTACCAGCAGCAAATGAGCACTGAGTTCAAGTCGGGCACTCTAGCTCGTTCGACAGGTTATCTTTGCCAGGCAGTGATCAGTTTGTCGAAGGTTACACAAAGCAGCCGAAAGCATCCCGCGTTACACCATAATAAGTCCCATTTACCAGGCCTGATAGGACGCTTGGCCTTGGTAGGTTGGCGGCCTCATGTTTGCGTCCCACGCGCGTCTAGTGTATTAGTATAACAGGGGCTTAGATGAAAATAAACAAAGAATTAATCAATGAACTAACCAACGAAGTAAGCAAGGATATACATAGATTTATTCATTGATCTATCCATCGATGTATGCATGGACACAGACTTACTCACTGACCTACCCACCGACGTACGCACGGAGAGTTAGTCAGTGAGCTAGCCAGCGAGGTAGGCAGGGTTTTCTTTGTTCCTTCGTTGCTTGGTCTCTGTCCCTCCGTCGCTCGGTGTGCCTGCGTGGCTGGGCCCCGCCGGCGCGGGGAAA";
	      int length = string.length();
	      ArrayList<String> dna =new ArrayList<String>();
	 
	      for(int c = 0 ; c < length ; c++ ){
	         for(int i = 1 ; i <= length - c ; i++ ){
	            sub = string.substring(c, c+i);
	            dna.add(sub);
	         }
	      }
	      String result = string;
	      //get the pattern
	      for(String temp : dna){
	    	 Pattern p = Pattern.compile(temp);
	    	 Matcher m = p.matcher(string2);
	    	 int count = 0;
	    	 while (m.find())
	    	     count++;
	    	  if(count == 0){
	    		 // System.out.println(temp);
	    		  if(result.length()>temp.length()){
	    			  result = temp;
	    		  }
	    	  }
	      }
	      System.out.println(result);
	   }
}
